Repository stolostron/search-api, pull requests merged in 2021-06, with the labels that each got.

#115 Add addonStatus to list properties
  src/v2/connectors/redisGraph.js
Labels: approved, do-not-merge/hold, lgtm

#116 update nodemon pkg
  package-lock.json
  package.json
  src/v2/lib/__snapshots__/errors.test.js.snap
  src/v2/lib/__snapshots__/rbacCaching.test.js.snap
  src/v2/lib/api.test.js
  src/v2/lib/errors.test.js
  src/v2/lib/rbacCaching.test.js
  src/v2/lib/utils.test.js
Labels: approved, do-not-merge/hold

#118 Fix setup.sh script
  setup.sh
Labels: approved, lgtm

#119 Change insightPolicies name to policyViolations
  src/v2/connectors/redisGraph.js
Labels: approved, do-not-merge/hold

#117 adding message query
  package-lock.json
  package.json
  src/v2/schema/__snapshots__/message.test.js.snap
  src/v2/schema/index.js
  src/v2/schema/message.js
  src/v2/schema/message.test.js
  src/v2/schema/query.js
  sslcert/req.conf
Labels: approved, lgtm

#120 Update dependencies (browserslist)
  package-lock.json
  package.json
Labels: approved, lgtm

#121 removed possibility for undefined in Message's id value
  src/v2/schema/message.js
Labels: approved, lgtm

#122 Fix operator status check
  src/v2/models/searchServiceStatus.js
Labels: approved, lgtm

#124 npm update packages
  package-lock.json
  package.json
Labels: approved, lgtm

#123 disabling CSP for development environment only.
  src/v2/index.js
Labels: approved, lgtm

#125 enabling hsts middleware
  src/v2/index.js
Labels: approved, lgtm
